package com.uk.accomodations.enums;

public enum UserState {
    AWAITING_NAME,
    AWAITING_REGION_SELECTION,
    AWAITING_POSTCODE_SELECTION,
    AWAITING_ACCOMMODATION_TYPE_SELECTION,
    OBTAINING_RESULTS,
    STOP_CONVERSATION
}
